// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyHcS1Gxkr8f8u14ivDR426ulmvdoIRF0',
    appId: '1:450595497053:web:2cd444f357196c7e9059b4',
    messagingSenderId: '450595497053',
    projectId: 'web-shoe-3d939',
    authDomain: 'web-shoe-3d939.firebaseapp.com',
    databaseURL: 'https://web-shoe-3d939-default-rtdb.firebaseio.com',
    storageBucket: 'web-shoe-3d939.firebasestorage.app',
    measurementId: 'G-R7QPMGRD27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj7SRzv--ZKvarcPeaDJBSRRIYnJ0FfiM',
    appId: '1:450595497053:android:452e0c36a2efe0bc9059b4',
    messagingSenderId: '450595497053',
    projectId: 'web-shoe-3d939',
    databaseURL: 'https://web-shoe-3d939-default-rtdb.firebaseio.com',
    storageBucket: 'web-shoe-3d939.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyHcS1Gxkr8f8u14ivDR426ulmvdoIRF0',
    appId: '1:450595497053:web:ae8b88e524ed565d9059b4',
    messagingSenderId: '450595497053',
    projectId: 'web-shoe-3d939',
    authDomain: 'web-shoe-3d939.firebaseapp.com',
    databaseURL: 'https://web-shoe-3d939-default-rtdb.firebaseio.com',
    storageBucket: 'web-shoe-3d939.firebasestorage.app',
    measurementId: 'G-S5BX75HVEN',
  );
}
